name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy types-requests

      - name: Run tests (headless Xvfb for Qt)
        env:
          PYTHONPATH: ${{ github.workspace }}
          # Use the offscreen platform plugin so Qt doesn't require a display
          QT_QPA_PLATFORM: offscreen
          # Disable Qt WebEngine sandbox in CI runners which can cause crashes
          QTWEBENGINE_DISABLE_SANDBOX: "1"
        run: |
          # Run tests under Xvfb so GUI libraries (Qt) have a display
          # Use xvfb-run which is available on ubuntu-latest images
          xvfb-run -s "-screen 0 1920x1080x24" pytest -q

      - name: Run mypy
        run: |
          python scripts/run_mypy.py
